### ISSUE TITLE
upper bound on splitmix in test is out of date

### ISSUE THREAD

**Issue by maralorn** [kowainik/trial#62]
Normally I would have just opened a PR to bump the bound, but "splitmix < 0.0.5" seems awfully specific.

Any reason not to bump this? It seems to compile and test just fine.

**Comment by chshersh** [comment]
The upper bound is not out of date, it's specified intentionally. Without this upper bound, another dependency `hspec-hedgehog` doesn't build on GHC-8.6.5 because of this issue:

* https://github.com/parsonsmatt/hspec-hedgehog/issues/10

As we maintain packages with older versions of GHC (at least the latest 3 major versions), this boundary is necessary to keep the compatibility. And we will keep the upper-bound on `splitmix` until other libraries fix their problems.
